apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-memorystore
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-memorystore.git
      sourceType: git
    version: 9.0.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
  content:
    subBlueprints:
      - name: memcache
        location: modules/memcache
      - name: redis-cluster
        location: modules/redis-cluster
    examples:
      - name: basic
        location: examples/basic
      - name: memcache
        location: examples/memcache
      - name: minimal
        location: examples/minimal
      - name: redis
        location: examples/redis
      - name: redis-cluster
        location: examples/redis-cluster
  interfaces:
    variables:
      - name: alternative_location_id
        description: The alternative zone where the instance will be provisioned.
        varType: string
      - name: auth_enabled
        description: Indicates whether OSS Redis AUTH is enabled for the instance. If set to true AUTH is enabled on the instance.
        varType: bool
        defaultValue: false
        connections:
        - source:
            source: https://github.com/terraform-google-modules/terraform-google-network//modules/vpc
            version: v9.1.0
          spec:
            output_expr: network_name
      - name: labels
        description: The resource labels to represent user provided metadata.
        varType: map(string)
      - name: maintenance_policy
        description: The maintenance policy for an instance.
        varType: |-
          object({
              day = string
              start_time = object({
                hours   = number
                minutes = number
                seconds = number
                nanos   = number
              })
            })
      - name: memory_size_gb
        description: Redis memory size in GiB. Defaulted to 1 GiB
        varType: number
        defaultValue: 1
      - name: name
        description: The ID of the instance or a fully qualified identifier for the instance.
        varType: string
        required: true
      - name: redis_configs
        description: The Redis configuration parameters. See [more details](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#Instance.FIELDS.redis_configs)
        varType: map(any)
        defaultValue: {}
      - name: redis_version
        description: The version of Redis software.
        varType: string
    outputs:
      - name: current_location_id
        description: The current zone where the Redis endpoint is placed.
        type: string
      - name: env_vars
        description: Exported environment variables
        type: [
          "object",
          {
            "REDIS_HOST": "string",
            "REDIS_PORT": "number"
          }
        ]
      - name: port
        description: The port number of the exposed Redis endpoint.
        type: number
      - name: read_endpoint
        description: " The IP address of the exposed readonly Redis endpoint."
        type: string
      - name: server_ca_certs
        description: List of server CA certificates for the instance
        type: [
          "list",
          [
            "object",
            {
              "cert": "string",
              "create_time": "string",
              "expire_time": "string",
              "serial_number": "string",
              "sha1_fingerprint": "string"
            }
          ]
        ]
  requirements:
    provider_versions:
      - source: hashicorp/google
        version: ">= 4.74.0, < 6"
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - serviceusage.googleapis.com
      - redis.googleapis.com
      - memcache.googleapis.com
      - serviceconsumermanagement.googleapis.com
      - networkconnectivity.googleapis.com
      - compute.googleapis.com
